SAM2017/paper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^submit$', views.submit, name="submit"),
    url(r'^submit/(?P<paper_id>[0-9]+)/', views.submit_file, name="submit_file"),
    url(r'^update/(?P<paper_id>[0-9]+)/$', views.update, name="update"),
    url(r'^submissions/(?P<paper_id>[0-9]+)/$', views.submissions, name="submissions"),
    url(r'^choose_paper$', views.choose_paper, name="choose_paper"),
    url(r'^chosen_papers$', views.chosen_papers, name="chosen_papers"),
    url(r'^my_papers/$', views.paper_listing, name="paper_listing"),
    url(r'^assign_paper/$',views.assign_paper,name="assign_paper"),
    url(r'^assign_pcm/(?P<paper_id>[0-9]+)/$', views.assign_pcm, name="assign_pcm"),
    url(r'^review_paper/$',views.review_paper,name="review_paper"),
]

SAM2017/rate_paper_pcm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.rate_paper_pcm, name='rate_paper_pcm'),
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.rate_paper_pcm_input_form, name='rate_paper_pcm_input_form'),
    url(r'^reviewed_papers/$', views.reviewed_papers,name='reviewed_papers'),
    url(r'^reviewed_papers/(?P<paper_id>[0-9]+)/$', views.pcc_rate_paper,name='pcc_rate_paper'),
    url(r'^resolve_conflict/(?P<paper_id>[0-9]+)/$',views.resolve_paper_conflict,name='resolve_paper_conflict'),
]

SAM2017/sam2017/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paper/', include('paper.urls', namespace='paper', app_name='paper')),
    url(r'^notification/', include('notification.urls', namespace='notification', app_name='notification')),
    url(r'^user_profile/$', include('user_profile.urls', namespace='user_profile', app_name='user_profile')),
    # url(r'^deadline/', include('deadline.urls', namespace='deadline', app_name='deadline')),
    url(r'^register/$', 'registration.views.register_user', name='registration'),
    url(r'^logout/$', views.logout_user, name='log_out'),
    url(r'rate_paper_pcm/', include('rate_paper_pcm.urls', namespace='rate_paper_pcm', app_name='rate_paper_pcm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAM2017/paper/models.py
from django.db import models
from registration.models import User
# Create your models here.


class Paper(models.Model):
    PHONE = "PHO"

    EMAIL = "EMA"

    contact_choices = (
        (PHONE, "Cell phone"),
        (EMAIL, "E-mail"),
    )

    PDF = "PDF"

    WORD = "WOR"

    format_choices = (
        (PDF, "Adobe PDF"),
        (WORD, "Microsoft Word"),
    )

    ALLOWED_FORMATS = ['pdf', 'doc', 'docx']

    submitter = models.ForeignKey(User, related_name='users', db_index=True)
    title = models.CharField(max_length=50)
    list_of_authors = models.CharField(max_length=150, help_text='Ex.: author1, author2, etc...')
    preferred_contact_method = models.CharField(max_length=3, choices=contact_choices)
    has_conflict = models.BooleanField(default=False)
    format = models.CharField(max_length=3, choices=format_choices)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    final_rating = models.IntegerField(null=True)

    def __str__(self):
        return str(self.id) + ': ' + self.title

    def get_contact_method(self):
        return dict(self.contact_choices).get(self.preferred_contact_method)

    def get_contact(self):
        if self.preferred_contact_method == self.PHONE:
            return "852-852-8520"

        elif self.preferred_contact_method == self.EMAIL:
            return self.submitter.email

    def get_format(self):
        return dict(self.format_choices).get(self.format)


class PCMs_Papers(models.Model):
    pcm = models.ForeignKey(User)
    paper = models.ForeignKey(Paper)
    is_assigned = models.BooleanField(default=False)

    def __str__(self):
        return 'Chosen paper ' + self.paper.title


class Submission(models.Model):
    file = models.FileField(upload_to="papers/%Y/%m/%d")
    paper = models.ForeignKey(Paper, related_name='submissions')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.paper.title


# class Notifications(models.Model):
#     sender = models.ForeignKey(User, related_name='Sender')
#     receiver = models.ForeignKey(User, related_name='Receiver')
#     message = models.TextField()
#     is_seen = models.BooleanField(default=False)
#
#     def __str__(self):
#         return str(self.id) + ': ' + self.sender.first_name

SAM2017/paper/forms.py
from django import forms
from . import models


class SubmitPaperForm(forms.ModelForm):

    file = forms.FileField(label="Select File", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = models.Paper
        fields = ['title', 'list_of_authors', 'preferred_contact_method', 'format', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'list_of_authors': forms.Textarea(attrs={'class': 'form-control resize-text-area-none', 'rows': 3}),
            'preferred_contact_method': forms.Select(attrs={'class': 'form-control'}),
            'format': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_title(self):
        return self.cleaned_data['title']

    def clean_list_of_authors(self):
        return self.cleaned_data['list_of_authors']

    def clean_version_number(self):
        return self.cleaned_data['version_number']

    def clean_format(self):
        return self.cleaned_data['format']

    def clean_file(self):
        if 'file' in self.cleaned_data:
            file_name = str(self.cleaned_data['file']).lower()
            file_parts = file_name.split(".")
            if not file_parts[-1] in ['pdf', 'doc', 'docx']:
                raise forms.ValidationError("Invalid file format.")
        return self.cleaned_data['file']


class UpdatePaperForm(forms.ModelForm):

    class Meta:
        model = models.Paper
        fields = ['title', 'list_of_authors', 'preferred_contact_method', 'format']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'list_of_authors': forms.Textarea(attrs={'class': 'form-control resize-text-area-none'}),
            'preferred_contact_method': forms.Select(attrs={'class': 'form-control'}),
            'format': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_title(self):
        return self.cleaned_data['title']

    def clean_list_of_authors(self):
        return self.cleaned_data['list_of_authors']

    def clean_version_number(self):
        return self.cleaned_data['version_number']

    def clean_format(self):
        return self.cleaned_data['format']

SAM2017/paper/views.py
from django.shortcuts import render
from registration.models import User
from registration.models import Role
from django.core.urlresolvers import reverse
from . import forms, models
from rate_paper_pcm.models import Paper_PCM_Rate
from deadline.models import Deadline
from notification.views import generate_notification_qty_num
from notification.models import Notifications
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.core import serializers
from django.conf import settings
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt


from sam2017.views import generate_name_role

import datetime

from django.views.decorators.csrf import csrf_exempt


def __default_context(user_identifier):
    context = {
        'show': True,
        'role': models.User.objects.get(email=user_identifier).role.code,
        'num_notification': generate_notification_qty_num(user_identifier),
    }
    return context


def submit(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    user = User.objects.get(email=request.session['user_identifier'])
    context = generate_name_role(user, __default_context(request.session['user_identifier']))
    if Deadline.objects.get(type='Submission_deadline').date < datetime.date.today():
        messages.warning(request, 'Submission deadline is over.')

        return render(request, "user_profile.html", context)
    paper = models.Paper()
    paper.submitter = user
    form = forms.SubmitPaperForm(request.POST or None, request.FILES or None, instance=paper)
    context = __default_context(request.session['user_identifier'])
    context['form'] = form
    context['submit'] = True
    context['btn_title'] = "Submit Paper"

    if request.method == 'POST':
        if form.is_valid():
            paper = form.save()
            submission = models.Submission(paper=paper)
            submission.file = request.FILES['file']
            submission.save()
            try:
                Notifications(
                    sender=user,
                    receiver=models.User.objects.get(role__code='PCC'),
                    message=user.first_name + ' ' + \

                            user.middle_initial + '. ' \
                            + user.last_name + ' submitted paper "' + paper.title + '".',
                ).save()
            except:
                pass

            messages.success(request, "Paper submitted successfully.")
            return HttpResponseRedirect('/paper/my_papers')
    return render(request, "paper/submit_form.html", context)


def choose_paper(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    pcm = User.objects.get(email=request.session['user_identifier'])
    chosen_papers = models.PCMs_Papers.objects.filter(pcm=pcm)
    assigned_papers = models.PCMs_Papers.objects.filter(is_assigned=True)
    papers = models.Paper.objects.exclude(id__in=[x.paper.id for x in chosen_papers]).exclude(submitter=pcm).exclude(
        id__in=[x.paper.id for x in assigned_papers])
    context = __default_context(request.session['user_identifier'])
    context['paper_list'] = papers
    context['choose'] = True
    if request.method == 'POST':
        chosen_papers = request.POST.getlist('papers')
        for c_paper in chosen_papers:
            paper = models.Paper.objects.get(pk=c_paper)
            paper_pcms = models.PCMs_Papers(paper=paper, pcm=pcm)
            paper_pcms.save()
        length = len(chosen_papers)

        if length == 1:
            messages.success(request, 'Paper has been successfully chosen.')
        else:
            messages.success(request, 'Papers have been successfully chosen.')
        return HttpResponseRedirect('choose_paper')

    return render(request, "paper/choose_paper.html", context)

def paper_listing(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))
    user = User.objects.get(email=request.session['user_identifier'])
    if user.role.code == user.role.PCC:
        papers = models.Paper.objects.all()
        context['paper_list'] = papers
    elif user.role.code == user.role.AUT or user.role.code == user.role.PCM:
        papers = models.Paper.objects.filter(submitter=user)
        context['paper_list'] = papers
        context['hide_to_author'] = True
        context['list_papers'] = True
    return render(request, "paper/paper_listing.html", context)

def assign_paper(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))

    context['assign'] = True
    assigned_papers = models.PCMs_Papers.objects.all().filter(is_assigned=True)
    paper = models.Paper.objects.all().exclude(id__in=[x.paper.id for x in assigned_papers])
    context['paper_list'] = paper
    return render(request, 'paper/paper_assignment.html', context)


def assign_pcm(request, paper_id):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))


    selected_paper = models.Paper.objects.get(pk=paper_id)
    paper_pcms = models.PCMs_Papers.objects.all().filter(paper=selected_paper)

    if len(paper_pcms) < 3:
        other_pcms = User.objects.filter(role=2).exclude(id__in=[u.pcm.id for u in paper_pcms])
        number_of_assigned_papers = []

        for u in other_pcms:
            number_of_assigned_papers.append(models.PCMs_Papers.objects.filter(pcm=u, is_assigned=True).count())

        return_val = zip(other_pcms, number_of_assigned_papers)

        context['other_pcms'] = return_val
        context['not_chosen_papers'] = True
    else:
        context['not_chosen_papers'] = False

    context['paper_pcms'] = paper_pcms
    context['assign'] = True
    if request.method == 'POST':
        chosen_pcms = request.POST.getlist('pcms')

        if len(chosen_pcms) != 3:
            context['error_message'] = 'Please assign three PCMs for the selected paper.'
        else:
            selected_paper = models.Paper.objects.get(pk=paper_id)
            for pcm in chosen_pcms:
                user = models.User.objects.get(id=pcm)
                try:
                    paper_pcm = models.PCMs_Papers.objects.get(paper=selected_paper, pcm=user)
                    paper_pcm.is_assigned = True
                    paper_pcm.save()
                except:
                    models.PCMs_Papers.objects.create(paper=selected_paper, pcm=user, is_assigned=True).save()
                Notifications(
                    sender=models.User.objects.get(email=request.session['user_identifier']),
                    receiver=user,
                    message='A paper with the title of ' + selected_paper.title,
                ).save()
            messages.success(request, 'You have successfully assigned paper PCMs.')
            return HttpResponseRedirect('/paper/assign_paper')

    return render(request, 'paper/pcm_assignment.html', context)


def update(request, paper_id):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')

    user = models.User.objects.get(email=request.session['user_identifier'])
    paper = models.Paper.objects.get(pk=paper_id)
    form = forms.UpdatePaperForm(request.POST or None, instance=paper)
    context = __default_context(request.session['user_identifier'])
    context['form'] = form
    context['btn_title'] = "Save Changes"
    context['submit'] = True
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            Notifications(
                sender=user,
                receiver=models.User.objects.get(role__code='PCC'),
                message='A paper with the title of ' + \
                        paper.title + ' has been updated by ' + \
                        user.first_name + ' ' + \
                        user.middle_initial + ' ' + user.last_name,
            ).save()

            Notifications(
                sender=user,
                receiver=models.User.objects.get(role__code='PCC'),
                message='A paper with the title of ' + \
                        paper.title + ' has been updated by ' + \
                        user.first_name + ' ' + \
                        user.middle_initial + ' ' + user.last_name,
            ).save()

            return HttpResponseRedirect('/paper/my_papers')
    return render(request, "paper/submit_form.html", context)


def submissions(request, paper_id):
    if 'user_identifier' not in request.session:
        return JsonResponse({'status_code': 500, 'message': 'An error happened when getting the submissions'})
    try:
        submissions_list = models.Submission.objects.filter(paper_id=paper_id).order_by('-created')
        data = serializers.serialize("json", submissions_list)

        response = {'statusCode': 200, 'message': 'OK', 'data': data, 'media': settings.MEDIA_URL, 'postURL': reverse("paper:submit_file", kwargs={'paper_id': paper_id})}
    except:
        response = {'status_code': 500, 'message': "An error happened when getting the submissions"}
    return JsonResponse(response)


def submit_file(request, paper_id):
    if 'user_identifier' not in request.session:
        return JsonResponse({'status_code': 500, 'message': 'An error happened when submitting'})

SAM2017/templates/paper/choose_paper.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-10 col-lg-offset-1">
            <h2 class="main-title text-align-center">Choose Papers to Review</h2>
            <hr />
            <form method="POST" action="">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="text-align-center">Select</th>
                                <th>Title</th>
                                <th>Submitter</th>
                                <th>Authors</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for paper in paper_list %}
                                <tr class="clickable-row-check" data-checkbox="{{ paper.id }}">
                                    <td class="text-align-center"><input type="checkbox" id="{{ paper.id }}" name="papers" value="{{ paper.id }}"></td>
                                    <td>{{ paper.title }}</td>
                                    <td>{{ paper.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                    <td>{{ paper.list_of_authors }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <p class="text-align-center"><button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> Save</button></p>
            </form>
        </div>
    </div>
{% endblock %}

SAM2017/templates/paper/chosen_papers.html
{% extends "base.html" %}
{% block content %}

    <!-- Start dialog box -->
            <div class="modal fade" id="reviewed" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Review</h4>
                        </div>
                        <div class="modal-body">

                            <span class="review">

                            </span>

                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-default btn-ok" data-dismiss="modal">Close</a>
                        </div>
                    </div>
                </div>
            </div>
    <!-- End dialog bog -->

    <div class="row">
        <div class="col-sm-10 col-lg-offset-1">
            <h2 class="main-title text-align-center">Chosen papers</h2>
            <hr />
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Submitter</th>
                                <th>Authors</th>
                                <th>Download</th>
                                <th>Review paper</th>
                                <th>Final rate</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for obj in reviewed_papers %}
                                <tr>
                                    <td>{{ obj.paper.title }}</td>
                                    <td>{{ obj.paper.submitter }}</td>
                                    <td>{{ obj.paper.list_of_authors }}</td>
                                    <td>
                                        <a href="{{ obj.paper.file.url }}" ><span class="glyphicon glyphicon glyphicon-download" aria-hidden="true"></span></a>
                                    </td>
                                    <td>
                                        {% if obj.has_conflict %}
                                            <a href=" {% url 'rate_paper_pcm:resolve_paper_conflict' obj.paper.id %}" class="btn btn-info btn-danger btn-block">Resolve conflict</a>

                                        {% else %}
                                            Reviewed
                                        {% endif %}
                                     </td>
                                    <td>
                                        {% ifequal obj.paper.final_rating None  %}
                                            Not rated
                                        {% else %}
                                            {% ifequal obj.paper.final_rating 0 %}
                                             <span style="color:red;">Rejected</span>

                                            {% endifequal %}

                                            {% ifequal obj.paper.final_rating 1 %}
                                             <span style="color:green;">Accepted</span>

                                            {% endifequal%}

                                            {% ifequal obj.paper.final_rating 2 %}
                                              <span style="color:lightgreen;">Accepted with modifications</span>

                                            {% endifequal %}
                                        {% endifequal %}
                                    </td>
                                </tr>
                            {% endfor %}

                            {% for obj in assigned_not_reviewed %}
                                <tr>
                                    <td>{{ obj.paper.title }}</td>
                                    <td>{{ obj.paper.submitter }}</td>
                                    <td>{{ obj.paper.list_of_authors }}</td>
                                    <td>
                                        <a href="{{ obj.paper.file.url }}" >
                                            <span class="glyphicon glyphicon glyphicon-download" aria-hidden="true"></span>
                                        </a>
                                    </td>
                                    <td>
                                        <a button class="btn btn-primary" href="/rate_paper_pcm/paper/{{ obj.paper.id }}/">Review</a>
                                    </td>
                                    <td>Not rated</td>
                                </tr>
                            {% endfor %}
                        {% for obj in chosen_papers %}
                            <tr>
                                <td>{{ obj.paper.title }}</td>
                                <td>{{ obj.paper.submitter }}</td>
                                <td>{{ obj.paper.list_of_authors }}</td>
                                <td>Not assigned</td>
                                <td>Not authorized</td>
                                <td>Not authorized</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
        </div>
    </div>

<script>
    $('#reviewed').on('show.bs.modal', function(e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        $('.delete').html('<strong>' + $(this).find('.btn-ok').attr('href') + '</strong>');

        $(this).find('.btn-ok').attr('review', $(e.relatedTarget).data('review'));
        $('.review').html($(this).find('.btn-ok').attr('review'));
    });
</script>

{% endblock %}

SAM2017/templates/paper/paper_assignment.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2 class="main-title text-align-center">Paper Listing</h2>
            <hr />
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Submitter</th>
                            <th>Authors</th>
                            <th>Contact</th>
                            <th style="text-align:center;">Assign</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for paper in paper_list %}
                            <tr>
                                <td>{{ paper.title }}</td>
                                <td>{{ paper.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                <td>{{ paper.list_of_authors }}</td>
                                <td>{{ paper.get_contact }}</td>
                                <td><a class="btn btn-primary btn-block"href="{% url "paper:assign_pcm" paper.id %}">Assign paper</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

SAM2017/templates/paper/paper_listing.html
{% extends "base.html" %}

{% block content %}

    {% include "paper/submissions_modal.html" %}

    <div class="row">
        <div class="col-sm-12">
            <h2 class="main-title text-align-center">Paper Listing</h2>
            <hr />
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            {% if not hide_to_author %}
                            <th>Submitter</th>
                            <th>Authors</th>
                            <th>Contact</th>
                            <th>Version</th>
                            <th>Date of submission</th>
                            <th>Format</th>
                            <th class="text-align-center">Submission</th>
                            {% else %}
                            <th>Authors</th>
                            <th>Contact via</th>
                            <th>Current Version</th>
                            <th>Date Submission</th>
                            <th>Format</th>
                            <th class="text-align-center">Submissions</th>
                            <th class="text-align-center">Update</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for paper in paper_list %}
                            <tr class="clickable-row-check">
                                <td>{{ paper.title }}</td>
                                {% if not hide_to_author %}
                                <td>{{ paper.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                <td>{{ paper.list_of_authors }}</td>
                                <td>{{ paper.get_contact }}</td>
                                <td>{{ paper.submissions.count }}</td>
                                <td>{{ paper.created }}</td>
                                <td>{{ paper.get_format }}</td>
                                <td class="text-align-center"><button id="{{ paper.id }}" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#subModal" data-url="{% url "paper:submissions" paper.id %}">{{ paper.submissions.count }}</button></td>
                                {% else %}
                                <td>{{ paper.list_of_authors }}</td>
                                <td>{{ paper.get_contact_method }}</td>
                                <td>{{ paper.submissions.count }}</td>
                                <td>{{ paper.created }}</td>
                                <td>{{ paper.get_format }}</td>
                                <td class="text-align-center"><button id="{{ paper.id }}" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#subModal" data-url="{% url "paper:submissions" paper.id %}">{{ paper.submissions.count }}</button></td>
                                <td class="text-align-center"><a href="{% url "paper:update" paper.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

SAM2017/templates/paper/pcm_reviewed_papers.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2 class="main-title text-align-center">Paper Listing</h2>
            <hr />
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Submitter</th>
                            <th>Authors</th>
                            <th>Contact</th>
                            <th>Review</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for paper in paper_list %}
                            <tr class="clickable-row-check">
                                <td>{{ paper.title }}</td>
                                <td>{{ paper.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                <td>{{ paper.list_of_authors }}</td>
                                <td>{{ paper.get_contact }}</td>
                                <td><a href="{% url "paper:assign_pcm" paper.id %}">Review paper</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}