SAM2017/paper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^submit$', views.submit, name="submit"),
    url(r'^submit/(?P<paper_id>[0-9]+)/', views.submit_file, name="submit_file"),
    url(r'^update/(?P<paper_id>[0-9]+)/$', views.update, name="update"),
    url(r'^submissions/(?P<paper_id>[0-9]+)/$', views.submissions, name="submissions"),
    url(r'^choose_paper$', views.choose_paper, name="choose_paper"),
    url(r'^chosen_papers$', views.chosen_papers, name="chosen_papers"),
    url(r'^my_papers/$', views.paper_listing, name="paper_listing"),
    url(r'^assign_paper/$',views.assign_paper,name="assign_paper"),
    url(r'^assign_pcm/(?P<paper_id>[0-9]+)/$', views.assign_pcm, name="assign_pcm"),
    url(r'^review_paper/$',views.review_paper,name="review_paper"),
]

SAM2017/rate_paper_pcm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.rate_paper_pcm, name='rate_paper_pcm'),
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.rate_paper_pcm_input_form, name='rate_paper_pcm_input_form'),
    url(r'^reviewed_papers/$', views.reviewed_papers,name='reviewed_papers'),
    url(r'^reviewed_papers/(?P<paper_id>[0-9]+)/$', views.pcc_rate_paper,name='pcc_rate_paper'),
    url(r'^resolve_conflict/(?P<paper_id>[0-9]+)/$',views.resolve_paper_conflict,name='resolve_paper_conflict'),
]

SAM2017/sam2017/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paper/', include('paper.urls', namespace='paper', app_name='paper')),
    url(r'^notification/', include('notification.urls', namespace='notification', app_name='notification')),
    url(r'^user_profile/$', include('user_profile.urls', namespace='user_profile', app_name='user_profile')),
    # url(r'^deadline/', include('deadline.urls', namespace='deadline', app_name='deadline')),
    url(r'^register/$', 'registration.views.register_user', name='registration'),
    url(r'^logout/$', views.logout_user, name='log_out'),
    url(r'rate_paper_pcm/', include('rate_paper_pcm.urls', namespace='rate_paper_pcm', app_name='rate_paper_pcm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAM2017/paper/models.py
from django.db import models
from registration.models import User
# Create your models here.


class Paper(models.Model):
    PHONE = "PHO"

    EMAIL = "EMA"

    contact_choices = (
        (PHONE, "Cell phone"),
        (EMAIL, "E-mail"),
    )

    PDF = "PDF"

    WORD = "WOR"

    format_choices = (
        (PDF, "Adobe PDF"),
        (WORD, "Microsoft Word"),
    )

    ALLOWED_FORMATS = ['pdf', 'doc', 'docx']

    submitter = models.ForeignKey(User, related_name='users', db_index=True)
    title = models.CharField(max_length=50)
    list_of_authors = models.CharField(max_length=150, help_text='Ex.: author1, author2, etc...')
    preferred_contact_method = models.CharField(max_length=3, choices=contact_choices)
    has_conflict = models.BooleanField(default=False)
    format = models.CharField(max_length=3, choices=format_choices)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    final_rating = models.IntegerField(null=True)

    def __str__(self):
        return str(self.id) + ': ' + self.title

    def get_contact_method(self):
        return dict(self.contact_choices).get(self.preferred_contact_method)

    def get_contact(self):
        if self.preferred_contact_method == self.PHONE:
            return "852-852-8520"

        elif self.preferred_contact_method == self.EMAIL:
            return self.submitter.email

    def get_format(self):
        return dict(self.format_choices).get(self.format)


class PCMs_Papers(models.Model):
    pcm = models.ForeignKey(User)
    paper = models.ForeignKey(Paper)
    is_assigned = models.BooleanField(default=False)

    def __str__(self):
        return 'Chosen paper ' + self.paper.title


class Submission(models.Model):
    file = models.FileField(upload_to="papers/%Y/%m/%d")
    paper = models.ForeignKey(Paper, related_name='submissions')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.paper.title


# class Notifications(models.Model):
#     sender = models.ForeignKey(User, related_name='Sender')
#     receiver = models.ForeignKey(User, related_name='Receiver')
#     message = models.TextField()
#     is_seen = models.BooleanField(default=False)
#
#     def __str__(self):
#         return str(self.id) + ': ' + self.sender.first_name

SAM2017/paper/forms.py
from django import forms
from . import models


class SubmitPaperForm(forms.ModelForm):

    file = forms.FileField(label="Select File", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = models.Paper
        fields = ['title', 'list_of_authors', 'preferred_contact_method', 'format', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'list_of_authors': forms.Textarea(attrs={'class': 'form-control resize-text-area-none', 'rows': 3}),
            'preferred_contact_method': forms.Select(attrs={'class': 'form-control'}),
            'format': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_title(self):
        return self.cleaned_data['title']

    def clean_list_of_authors(self):
        return self.cleaned_data['list_of_authors']

    def clean_version_number(self):
        return self.cleaned_data['version_number']

    def clean_format(self):
        return self.cleaned_data['format']

    def clean_file(self):
        if 'file' in self.cleaned_data:
            file_name = str(self.cleaned_data['file']).lower()
            file_parts = file_name.split(".")
            if not file_parts[-1] in ['pdf', 'doc', 'docx']:
                raise forms.ValidationError("Invalid file format.")
        return self.cleaned_data['file']


class UpdatePaperForm(forms.ModelForm):

    class Meta:
        model = models.Paper
        fields = ['title', 'list_of_authors', 'preferred_contact_method', 'format']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'list_of_authors': forms.Textarea(attrs={'class': 'form-control resize-text-area-none'}),
            'preferred_contact_method': forms.Select(attrs={'class': 'form-control'}),
            'format': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_title(self):
        return self.cleaned_data['title']

    def clean_list_of_authors(self):
        return self.cleaned_data['list_of_authors']

    def clean_version_number(self):
        return self.cleaned_data['version_number']

    def clean_format(self):
        return self.cleaned_data['format']

SAM2017/paper/views.py
from django.shortcuts import render
from registration.models import User
from registration.models import Role
from django.core.urlresolvers import reverse
from . import forms, models
from rate_paper_pcm.models import Paper_PCM_Rate
from deadline.models import Deadline
from notification.views import generate_notification_qty_num
from notification.models import Notifications
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.core import serializers
from django.conf import settings
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt


from sam2017.views import generate_name_role

import datetime

from django.views.decorators.csrf import csrf_exempt


def __default_context(user_identifier):
    context = {
        'show': True,
        'role': models.User.objects.get(email=user_identifier).role.code,
        'num_notification': generate_notification_qty_num(user_identifier),
    }
    return context


def submit(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    user = User.objects.get(email=request.session['user_identifier'])
    context = generate_name_role(user, __default_context(request.session['user_identifier']))
    if Deadline.objects.get(type='Submission_deadline').date < datetime.date.today():
        messages.warning(request, 'Submission deadline is over.')

        return render(request, "user_profile.html", context)
    paper = models.Paper()
    paper.submitter = user
    form = forms.SubmitPaperForm(request.POST or None, request.FILES or None, instance=paper)
    context = __default_context(request.session['user_identifier'])
    context['form'] = form
    context['submit'] = True
    context['btn_title'] = "Submit Paper"

    if request.method == 'POST':
        if form.is_valid():
            paper = form.save()
            submission = models.Submission(paper=paper)
            submission.file = request.FILES['file']
            submission.save()
            try:
                Notifications(
                    sender=user,
                    receiver=models.User.objects.get(role__code='PCC'),
                    message=user.first_name + ' ' + \

                            user.middle_initial + '. ' \
                            + user.last_name + ' submitted paper "' + paper.title + '".',
                ).save()
            except:
                pass

            messages.success(request, "Paper submitted successfully.")
            return HttpResponseRedirect('/paper/my_papers')
    return render(request, "paper/submit_form.html", context)


def choose_paper(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    pcm = User.objects.get(email=request.session['user_identifier'])
    chosen_papers = models.PCMs_Papers.objects.filter(pcm=pcm)
    assigned_papers = models.PCMs_Papers.objects.filter(is_assigned=True)
    papers = models.Paper.objects.exclude(id__in=[x.paper.id for x in chosen_papers]).exclude(submitter=pcm).exclude(
        id__in=[x.paper.id for x in assigned_papers])
    context = __default_context(request.session['user_identifier'])
    context['paper_list'] = papers
    context['choose'] = True
    if request.method == 'POST':
        chosen_papers = request.POST.getlist('papers')
        for c_paper in chosen_papers:
            paper = models.Paper.objects.get(pk=c_paper)
            paper_pcms = models.PCMs_Papers(paper=paper, pcm=pcm)
            paper_pcms.save()
        length = len(chosen_papers)

        if length == 1:
            messages.success(request, 'Paper has been successfully chosen.')
        else:
            messages.success(request, 'Papers have been successfully chosen.')
        return HttpResponseRedirect('choose_paper')

    return render(request, "paper/choose_paper.html", context)

def paper_listing(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))
    user = User.objects.get(email=request.session['user_identifier'])
    if user.role.code == user.role.PCC:
        papers = models.Paper.objects.all()
        context['paper_list'] = papers
    elif user.role.code == user.role.AUT or user.role.code == user.role.PCM:
        papers = models.Paper.objects.filter(submitter=user)
        context['paper_list'] = papers
        context['hide_to_author'] = True
        context['list_papers'] = True
    return render(request, "paper/paper_listing.html", context)

def assign_paper(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))

    context['assign'] = True
    assigned_papers = models.PCMs_Papers.objects.all().filter(is_assigned=True)
    paper = models.Paper.objects.all().exclude(id__in=[x.paper.id for x in assigned_papers])
    context['paper_list'] = paper
    return render(request, 'paper/paper_assignment.html', context)


def assign_pcm(request, paper_id):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    context = generate_name_role(models.User.objects.get(email=request.session['user_identifier']),
                                 __default_context(request.session['user_identifier']))


    selected_paper = models.Paper.objects.get(pk=paper_id)
    paper_pcms = models.PCMs_Papers.objects.all().filter(paper=selected_paper)

    if len(paper_pcms) < 3:
        other_pcms = User.objects.filter(role=2).exclude(id__in=[u.pcm.id for u in paper_pcms])
        number_of_assigned_papers = []

        for u in other_pcms:
            number_of_assigned_papers.append(models.PCMs_Papers.objects.filter(pcm=u, is_assigned=True).count())

        return_val = zip(other_pcms, number_of_assigned_papers)

        context['other_pcms'] = return_val
        context['not_chosen_papers'] = True
    else:
        context['not_chosen_papers'] = False

    context['paper_pcms'] = paper_pcms
    context['assign'] = True
    if request.method == 'POST':
        chosen_pcms = request.POST.getlist('pcms')

        if len(chosen_pcms) != 3:
            context['error_message'] = 'Please assign three PCMs for the selected paper.'
        else:
            selected_paper = models.Paper.objects.get(pk=paper_id)
            for pcm in chosen_pcms:
                user = models.User.objects.get(id=pcm)
                try:
                    paper_pcm = models.PCMs_Papers.objects.get(paper=selected_paper, pcm=user)
                    paper_pcm.is_assigned = True
                    paper_pcm.save()
                except:
                    models.PCMs_Papers.objects.create(paper=selected_paper, pcm=user, is_assigned=True).save()
                Notifications(
                    sender=models.User.objects.get(email=request.session['user_identifier']),
                    receiver=user,
                    message='A paper with the title of ' + selected_paper.title,
                ).save()
            messages.success(request, 'You have successfully assigned paper PCMs.')
            return HttpResponseRedirect('/paper/assign_paper')

    return render(request, 'paper/pcm_assignment.html', context)


def update(request, paper_id):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')

    user = models.User.objects.get(email=request.session['user_identifier'])
    paper = models.Paper.objects.get(pk=paper_id)
    form = forms.UpdatePaperForm(request.POST or None, instance=paper)
    context = __default_context(request.session['user_identifier'])
    context['form'] = form
    context['btn_title'] = "Save Changes"
    context['submit'] = True
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            Notifications(
                sender=user,
                receiver=models.User.objects.get(role__code='PCC'),
                message='A paper with the title of ' + \
                        paper.title + ' has been updated by ' + \
                        user.first_name + ' ' + \
                        user.middle_initial + ' ' + user.last_name,
            ).save()

            Notifications(
                sender=user,
                receiver=models.User.objects.get(role__code='PCC'),
                message='A paper with the title of ' + \
                        paper.title + ' has been updated by ' + \
                        user.first_name + ' ' + \
                        user.middle_initial + ' ' + user.last_name,
            ).save()

            return HttpResponseRedirect('/paper/my_papers')
    return render(request, "paper/submit_form.html", context)


def submissions(request, paper_id):
    if 'user_identifier' not in request.session:
        return JsonResponse({'status_code': 500, 'message': 'An error happened when getting the submissions'})
    try:
        submissions_list = models.Submission.objects.filter(paper_id=paper_id).order_by('-created')
        data = serializers.serialize("json", submissions_list)

        response = {'statusCode': 200, 'message': 'OK', 'data': data, 'media': settings.MEDIA_URL, 'postURL': reverse("paper:submit_file", kwargs={'paper_id': paper_id})}
    except:
        response = {'status_code': 500, 'message': "An error happened when getting the submissions"}
    return JsonResponse(response)


def submit_file(request, paper_id):
    if 'user_identifier' not in request.session:
        return JsonResponse({'status_code': 500, 'message': 'An error happened when submitting'})

SAM2017/templates/paper/rate_paper_pcc/pcc_rate_paper.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
            <div class="paper-information" style="margin-bottom:30px;">
                <h3>Paper author:{{ paper_author}}</h3>
                <h3>Paper title:{{ paper_title}}</h3>
            </div>
            {% if paper_reviews %}
                {% for obj in paper_reviews %}
                    <div class="col-md-6 col-md-offset-1">
                        <h4 >Reviewer: {{ obj.pcm.first_name }} </h4>
                        <p class="img-thumbnail col-md-12" style="padding:3%;">{{ obj.review }}</p>
                    </div>
                    <div class="col-md-2">
                        <h4>Rating</h4>
                        <p class="col-md-12" style="padding:3%;">
                            {% ifequal obj.decision 0 %}
                             Reviewer <span style="color:red;">rejected</span> the paper.
                            {% endifequal %}
                            {% ifequal obj.decision 1 %}
                             Reviewer <span style="color:green;">accepted</span> the paper.
                            {% endifequal%}
                            {% ifequal obj.decision 2 %}
                             Reviewer <span style="color:lightgreen;">accepted with modifications</span> the paper.
                            {% endifequal %}
                        </p>
                    </div>
                {% endfor %}
            {% else %}
                        <h2>There has not been any paper reviewed.</h2>
            {% endif %}
    </div>
    <div class="row" style="margin-bottom:20px;">
        <div class="col-md-4 col-md-offset-1">
            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary" name="form-type" value="rate_form" type="submit">Rate Paper</button>
            </form>
        </div>
        <div class="col-md-4">
            <div style="margin-top:80px">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>Paper has conflict?</h4>
                    <button class="btn btn-danger" name="form-type" value="issue_form" type="submit">Issue paper review conflict</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

SAM2017/templates/paper/rate_paper_pcc/resolve_conflict.html
{% extends "base.html" %}
{% block content %}
	<h6>Resolving conflict for {{paper_title}}</h6>
            <h2>Other paper reviews</h2>

	<div class="row">"
    {% for obj in paper_reviews %}
        <div class="col-md-6 col-md-offset-1">
            <h4 >Reviewer: {{ obj.pcm.first_name }} </h4>
            <p class="img-thumbnail col-md-12" style="padding:3%;">{{ obj.review }}</p>
        </div>
        <div class="col-md-2">
            <h4>Rating</h4>
            <p class="col-md-12" style="padding:3%;">
                {% ifequal obj.decision 0 %}
                    Reviewer <span style="color:red;">rejected</span> the paper.
                {% endifequal %}
                {% ifequal obj.decision 1 %}
                    Reviewer <span style="color:green;">accepted</span> the paper.
                {% endifequal%}
                {% ifequal obj.decision 2 %}
                    Reviewer <span style="color:lightgreen;">accepted with modifications</span> the paper.
                {% endifequal %}
            </p>
        </div>
    {% endfor %}
    <div class="col-md-8">
			<form method="post" action="">
				{% csrf_token %}
				{{review_form.as_p}}
				<p class="text-align-center"><button class="btn btn-primary" type="submit">Submit review</button></p>
			</form>
		</div>
	</div>
{% endblock %}

SAM2017/templates/paper/rate_paper_pcc/reviewed_papers_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h2 class="main-title text-align-center">Reviewed Papers</h2>
            <hr />
            <div class="table-responsive">
            {% if reviewed_papers %}
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Submitter</th>
                            <th>Authors</th>
                            <th>Contact</th>
                            <th>Reviews</th>
                            <th >Rate paper</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p,r in reviewed_papers %}
                            <tr>
                                <td>{{ p.title }}</td>
                                <td>{{ p.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                <td>{{ p.list_of_authors }}</td>
                                <td>{{ p.get_contact }}</td>
                                <td>{{ r}}</td>
                                <td>
                                    {% if p.has_conflict %}
                                        Conflict is being resolved
                                    {% else %}
                                        {% if p.final_rating == 1 or p.final_rating == 2 or p.final_rating == 0 %}Rated
                                        {% else %}
                                            {% ifequal r 3 %}
                                                <a class="btn btn-block btn-primary" href="{% url "rate_paper_pcm:pcc_rate_paper" p.id %}">Rate paper</a></td>
                                                {% else %}
                                                    Missing review/s
                                            {% endifequal %}
                                        {% endif %}
                                    {% endif %}
                            </tr>
                        {% endfor %}
                        {% for p in not_reviewed_papers %}
                            <tr>
                            <td>{{ p.title }}</td>
                                <td>{{ p.submitter.first_name }} {{ paper.submitter.last_name }}</td>
                                <td>{{ p.list_of_authors }}</td>
                                <td>{{ p.get_contact }}</td>
                                <td>No reviews</td>
                                <td>Cannot rate </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
               {% else %}
                        <h2>There has not been any paper reviewed.</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}