SAM2017/paper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^submit$', views.submit, name="submit"),
    url(r'^submit/(?P<paper_id>[0-9]+)/', views.submit_file, name="submit_file"),
    url(r'^update/(?P<paper_id>[0-9]+)/$', views.update, name="update"),
    url(r'^submissions/(?P<paper_id>[0-9]+)/$', views.submissions, name="submissions"),
    url(r'^choose_paper$', views.choose_paper, name="choose_paper"),
    url(r'^chosen_papers$', views.chosen_papers, name="chosen_papers"),
    url(r'^my_papers/$', views.paper_listing, name="paper_listing"),
    url(r'^assign_paper/$',views.assign_paper,name="assign_paper"),
    url(r'^assign_pcm/(?P<paper_id>[0-9]+)/$', views.assign_pcm, name="assign_pcm"),
    url(r'^review_paper/$',views.review_paper,name="review_paper"),
]

SAM2017/rate_paper_pcm/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.rate_paper_pcm, name='rate_paper_pcm'),
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.rate_paper_pcm_input_form, name='rate_paper_pcm_input_form'),
    url(r'^reviewed_papers/$', views.reviewed_papers,name='reviewed_papers'),
    url(r'^reviewed_papers/(?P<paper_id>[0-9]+)/$', views.pcc_rate_paper,name='pcc_rate_paper'),
    url(r'^resolve_conflict/(?P<paper_id>[0-9]+)/$',views.resolve_paper_conflict,name='resolve_paper_conflict'),
]

SAM2017/sam2017/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paper/', include('paper.urls', namespace='paper', app_name='paper')),
    url(r'^notification/', include('notification.urls', namespace='notification', app_name='notification')),
    url(r'^user_profile/$', include('user_profile.urls', namespace='user_profile', app_name='user_profile')),
    # url(r'^deadline/', include('deadline.urls', namespace='deadline', app_name='deadline')),
    url(r'^register/$', 'registration.views.register_user', name='registration'),
    url(r'^logout/$', views.logout_user, name='log_out'),
    url(r'rate_paper_pcm/', include('rate_paper_pcm.urls', namespace='rate_paper_pcm', app_name='rate_paper_pcm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAM2017/user_profile/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', 'user_profile.views.profile', name="user_profile"),
]

SAM2017/user_profile/models.py
from django.db import models

# Create your models here.

SAM2017/rate_paper_pcm/forms.py
from . import models
from django import forms


def get_rate_choices():
    choices = [(0, 'Rejected'), (1, 'Accepted'), (2, 'Accepted with modification')]
    return choices


class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.Paper_PCM_Rate
        fields = ['review']
        widgets = {
            'review': forms.Textarea(attrs={'class': 'form-control'}),
        }

    CHOICES = [(0, 'Rejected'), (1, 'Accepted'), (2, 'Accepted with modification')]

    final_decision = forms.ChoiceField(choices=get_rate_choices(), widget=forms.RadioSelect())

    def set_paper(self, paper):
        self.instance.paper = paper

    def set_pcm(self, pcm):
        self.instance.pcm = pcm

    def set_decision(self, decision):
        self.instance.decision = decision

    def clean_review(self):
        return self.cleaned_data['review']


class FinalRatingForm(forms.Form):
    CHOICES = [(0, 'Rejected'), (1, 'Accepted'), (2, 'Accepted with modification')]
    final_decision = forms.ChoiceField(choices=get_rate_choices(), widget=forms.RadioSelect())

SAM2017/user_profile/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from registration import models
from notification.views import generate_notification_qty_num
from deadline.models import Deadline
from django.contrib import messages
import time, datetime
from sam2017.views import generate_name_role


def __default_context(request, user_identifier):
    user = models.User.objects.get(email=user_identifier)

    context = {
        'show': True,
        'role': user.role.code,
        'num_notification': generate_notification_qty_num(user_identifier),
    }

    return generate_name_role(user, context)


def verify_daily_notifications(request, code):
    prev_date = Deadline.objects.get(type='Notification_deadline')
    today = datetime.date.today()
    update = False
    if prev_date.date < today:
        if code == 'PCC':
            pass
            # update = True
        elif True:
            pass
        else:
            pass

    if update:
        prev_date.date = today
        prev_date.save()


def verify_daily_notifications(request, code):
    prev_date = Deadline.objects.get(type='X')
    today = datetime.date.today()
    update = False

    if prev_date.date < today:
        if code == 'PCC':
            messages.warning(request, "Review for PCC.")
            update = True

        elif True:
            pass

        else:
            pass

    if update:
        prev_date.date = today
        prev_date.save()


def profile(request):
    if 'user_identifier' not in request.session:
        return HttpResponseRedirect('/')
    verify_daily_notifications(request, models.User.objects.get(email=request.session['user_identifier']).role.code)
    context = __default_context(request, request.session['user_identifier'])

    return render(request, 'user_profile.html', context)

SAM2017/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/favicon.ico" %}">

    <title>{% block head_title %}SAM2017{% endblock %}</title>

    {% include "head_css.html" %}

    <style>
    {% block style %}

    {% endblock %}
    </style>
  </head>

  <body class="min-body-height">
    {% include "navbar.html" %}
    <div class="container" style="padding-top:0;">
        {% block jumbotron %}
        {% endblock %}
        {% block content %}

        {% endblock %}
    </div> <!-- /container -->

    <footer class="footer">
      <div class="container">
        <p class="text-muted text-align-center">Created by Uncaught Exception Team &copy; 2015 | Copyright All Rights Reserved</p>
      </div>
    </footer>

    {% include "javascript.html" %}

  </body>
</html>

SAM2017/templates/head_css.html
{% load staticfiles %}
<!-- Bootstrap core CSS -->
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static "css/jquery-ui.min.css" %}" rel="stylesheet">
<link href="{% static "css/navbar-static-top.css" %}" rel="stylesheet">
<link href="{% static "css/custom.css" %}" rel="stylesheet">
<link href="{% static "css/sticky-footer-navbar.css" %}" rel="stylesheet">
<link href="{% static "css/signin.css" %}" rel="stylesheet">

<style>
    <!--.bold{-->
        <!--font-weight: bold;-->
    <!--}-->

    <!--.error{-->
        <!--background-color: #ff9999;-->
    <!--}-->

    <!--.delete-bottom{-->
        <!--color: #bfbfbf;-->
    <!--}-->

    <!--.delete-bottom:hover{-->
        <!--color: #ff6666;-->
    <!--}-->

    <!--#id_final_decision{-->
        <!--list-style: none;-->
    <!--}-->
</style>

SAM2017/templates/home.html
    {% extends "base.html" %}
    {% load staticfiles %}
    {% block head_title %}{{ Welcome }} | {{ block.super }}{% endblock %}

    {% block content %}
        <div class="row">
            <h2 class="main-title">Log In</h2>
            <div class="col-md-4">
                <form method="POST" action="">
                    {% csrf_token %}
                    {{ login_form.as_p }}
                    <button type="submit" class="btn btn-primary">Log In <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span></button>
                </form>
            </div>
        </div>
    {% endblock %}

SAM2017/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}" ></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script src="{% static "js/angular.min.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>

SAM2017/templates/navbar.html
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'user_profile:user_profile' %}" class="navbar-brand"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> SAM2017</a></li>
            {% if show %}

              {% if role == 'AUT' or role == 'PCM' %}
                <li class="{% if submit %}active{% endif %}"><a href="{% url "paper:submit" %}"><span class="glyphicon glyphicon-open-file" aria-hidden="true"></span> Submit Paper</a></li>
                <li class="{% if list_papers %}active{% endif %}"><a href="{% url "paper:paper_listing" %}"><span class="glyphicon glyphicon-level-up" aria-hidden="true"></span> My Papers</a></li>
              {% endif %}

              {% if role == 'PCM' %}
                <li class="{% if choose %}active{% endif %}"><a href="{% url "paper:choose_paper" %}"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Choose Paper</a></li>
                <li class="{% if review_paper_pcm %}active{% endif %}"><a href=" {%  url "paper:chosen_papers"  %}"><span class="glyphicon glyphicon-file"></span> Papers</a></li>
              {% endif %}

               {% if role == 'PCC' %}
                <li class="{% if assign %}active{% endif %}"><a href="{% url "paper:assign_paper" %}"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Assign Paper</a></li>
                <li class="{% if list_papers %}active{% endif %}"><a href="{% url "paper:paper_listing" %}"><span class="glyphicon glyphicon-level-up" aria-hidden="true"></span> Submitted Papers</a></li>
                <li class="{% if reviewed %}active{% endif %}"><a href="{% url "rate_paper_pcm:reviewed_papers" %}"></span> Rate paper</a></li>
              {% endif %}

              <li class="{% if notifications %}active{% endif %}"><a href="{% url 'notification:notification' %}"><span class="glyphicon glyphicon-level-up" aria-hidden="true"></span> Notifications [ {{ num_notification }} ]</a></li>
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if show %}
                <li><a href="{% url 'log_out' %}">{{ name }} - {{ user_role }} | Log Out <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
            {% else %}
                <li><a href="{{ link }}">{{ link_name }} <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% if messages %}
        <b class="messages">
            {% for msg in messages %}
                <div class="alert alert-{{msg.level_tag}}" role="alert">
                    {{msg.message}}
                    <a data-dismiss="alert" aria-hidden="true" class="close glyphicon glyphicon-remove"></a>
                </div>
            {% endfor %}</b>
    {% endif %}

SAM2017/templates/registration.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <form method="POST" action="">
                {% csrf_token %}
                {{ registration_form.as_p }}
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Register
                </button>
            </form>
        </div>
    </div>
    <br>
{% endblock %}

SAM2017/templates/user_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{{ Profile }} | {{ block.super }}{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            Conference Information
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        <span class="bold">Workshop name:</span>
                    </td>
                    <td>
                        Software Architecture Mining
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="bold">Time:</span>
                    </td>
                    <td>
                        6:30 PM
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="bold">Location:</span>
                    </td>
                    <td>
                        Central Park, N.Y.
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}