SAM2017/notification/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^notification/$', views.notifications, name='notification'),
    url(r'^delete/(?P<notification_id>[0-9]+)/$', views.delete_notification, name='delete_notification'),
]

SAM2017/paper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^submit$', views.submit, name="submit"),
    url(r'^submit/(?P<paper_id>[0-9]+)/', views.submit_file, name="submit_file"),
    url(r'^update/(?P<paper_id>[0-9]+)/$', views.update, name="update"),
    url(r'^submissions/(?P<paper_id>[0-9]+)/$', views.submissions, name="submissions"),
    url(r'^choose_paper$', views.choose_paper, name="choose_paper"),
    url(r'^chosen_papers$', views.chosen_papers, name="chosen_papers"),
    url(r'^my_papers/$', views.paper_listing, name="paper_listing"),
    url(r'^assign_paper/$',views.assign_paper,name="assign_paper"),
    url(r'^assign_pcm/(?P<paper_id>[0-9]+)/$', views.assign_pcm, name="assign_pcm"),
    url(r'^review_paper/$',views.review_paper,name="review_paper"),
]

SAM2017/sam2017/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paper/', include('paper.urls', namespace='paper', app_name='paper')),
    url(r'^notification/', include('notification.urls', namespace='notification', app_name='notification')),
    url(r'^user_profile/$', include('user_profile.urls', namespace='user_profile', app_name='user_profile')),
    # url(r'^deadline/', include('deadline.urls', namespace='deadline', app_name='deadline')),
    url(r'^register/$', 'registration.views.register_user', name='registration'),
    url(r'^logout/$', views.logout_user, name='log_out'),
    url(r'rate_paper_pcm/', include('rate_paper_pcm.urls', namespace='rate_paper_pcm', app_name='rate_paper_pcm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAM2017/notification/models.py
from django.db import models
from registration.models import User

import datetime


# Create your models here.
class Notifications(models.Model):
    sender = models.ForeignKey(User, related_name='Sender')
    receiver = models.ForeignKey(User, related_name='Receiver')
    message = models.TextField()
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return str(self.id) + ': ' + self.sender.first_name

SAM2017/notification/views.py
from django.shortcuts import render
from registration.models import User

from . import models

from sam2017.views import generate_name_role


# ---------------------------------
# generates the notification number
# ---------------------------------
def generate_notification_qty_num(email):
    return models.Notifications.objects.filter(receiver=User.objects.get(email=email)).count()

# end generate_notification_qty_num function


# ------------------------
# returns a common context
# ------------------------
def return_render(request, user):
    context = {
        'show': True,
        'notifications': True,
        'role': user.role.code,
        'notifications_messages': models.Notifications.objects.all().filter(receiver=user),
        'num_notification': generate_notification_qty_num(request.session['user_identifier']),
    }

    context = generate_name_role(user, context) # updates the context

    return render(request, 'notification/notification.html', context)

# end return_render function


# -----------------------------------
# generates the notification template
# -----------------------------------
def notifications(request):
    user = User.objects.get(email=request.session['user_identifier'])

    return return_render(request, user)

# end notifications function


# --------------------------------------
# generates delete_notification function
# --------------------------------------
def delete_notification(request, notification_id):
    models.Notifications.objects.get(id=notification_id).delete()

    user = User.objects.get(email=request.session['user_identifier'])

    return return_render(request, user)

# end delete_notification function

SAM2017/templates/notification/notification.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{{ Profile }} | {{ block.super }}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <h2 class="main-title text-align-center">Notifications</h2>
            <hr />
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Sender</th>
                            <th>Created at</th>
                            <th>Message</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for notification in notifications_messages %}
                            <tr>
                                <td>
                                    {{ notification.sender.first_name }}
                                    {{ notification.sender.middle_initial }}
                                    {{ notification.sender.last_name }}
                                </td>
                                <td>
                                    {{ notification.timestamp }}
                                </td>
                                <td>
                                    {{ notification.message }}
                                </td>
                                <td>
                                    <a href="{% url 'notification:delete_notification' notification.id %}">
                                        <span class="glyphicon glyphicon-remove delete-bottom"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}